
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/shyue/cmake-3.30.7-linux-x86_64/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.4.0-150-generic - x86_64
...
